name: Events n Filters

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
  pull_request:
    branches:
      - main
    paths:
      - "README.md"

jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - run: echo "Hello from $GITHUB_EVENT_NAME on $GITHUB_REF"
      - run: git status
